### ISSUE TITLE
Refactor to utilise Nextflow's staging of files power and omit wget

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/simulate#15]
The current implementation only allows for the use of https or ftp links to files. Ideally we want to support all 3 types:
- https or ftp
- cloud vendor file, eg s3 for aws, gs for google
- (_less important_) local file, for local tests

Refactor to stage the files with `Channel.fromPath` and omit wget.

https://github.com/lifebit-ai/simulate/blob/6041fbd805b7699c5f75ba8ff15f4b3dc5d3481a/main.nf#L119-L160

**Comment by mmeier93** [comment]
Addressed in PR: https://github.com/lifebit-ai/simulate/pull/24
