### ISSUE TITLE
VCF files should retain the vcf suffix

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/simulate#25]
Not a bug but a critical enhancement, since many subsequent tools will complain about the suffix, first in line being IGV.
https://github.com/lifebit-ai/simulate/blob/12520c62415fc326b580393837b3a2a49413326e/main.nf#L280

https://cloudos.lifebit.ai/app/jobs/5fb59358cc96a201128df7c7

![image](https://user-images.githubusercontent.com/38183826/99646086-f6683080-2a47-11eb-9813-ae2bc5536563.png)

**Comment by mmeier93** [comment]
Addressed in PR: https://github.com/lifebit-ai/simulate/pull/24
